name: repice_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.5
  flutter_bloc: ^9.1.0
  cached_network_image: ^3.4.1
  http: ^1.2.1
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/